#!/usr/bin/env node
/**
 * Route-driven API suite.
 *
 * Reads the full route table (generated by /tmp/route-inventory.js) and exercises
 * every GET endpoint, plus a non-destructive probe of every write endpoint.
 *
 * Two tiers:
 *   READ   — every GET route, called for real. A 404/400 that means "no such
 *            record" is counted as ABSENT (endpoint is wired correctly).
 *   PROBE  — every POST/PUT/PATCH route called with an empty body. A validation
 *            rejection (400/422) proves the route is wired AND its handler runs.
 *            A 404 means the route is missing; a 500 means the handler crashed.
 *            Endpoints that actually accepted the empty body are reported as
 *            WROTE so they are never silently mistaken for passing validation.
 *
 *   node test-api.js            # run everything
 *   node test-api.js --list     # print the route table and exit
 *   node test-api.js --no-probe # GET coverage only
 */

const http = require("http");

const BASE = process.env.API_BASE || "http://localhost:5002";
const ROUTES_FILE = "/tmp/routes.json";
const TIMEOUT_MS = 12000;

// ── probe values for :params ────────────────────────────────────────────────
const PARAM_PROBES = {
  id: "1",
  bookingId: "1",
  customerId: "1",
  userId: "1",
  roomNumber: "101",
  tableNumber: "1",
  orderId: "1",
  tokenId: "1",
  menuItemId: "1",
  sectionKey: "inventory-categories",
  table: "1",
  code: "TEST",
};

// Endpoints safe to call without mutating meaningfully, or that are idempotent
// reads dressed as POST (report builders, availability checks, logins).
const SAFE_WRITES = [
  { method: "POST", path: "/api/auth/login", body: { email: "admin@resort.com", password: "password" } },
];

// Write routes never fired with an empty body: sending a destructive or
// side-effecting payload to a live database is not a test, it is data loss.
// These are covered by the read tier (their GET siblings) or verified by hand.
const SKIP_PROBE_PREFIXES = [
  "/api/auth/",           // register creates accounts
  "/api/print/",          // talking to printers
  "/api/banquet/invoice", // sends WhatsApp messages
  "/api/restaurant/invoice",
  "/api/whatsapp",
];

// A probe rejection: the route exists, the handler ran, and it refused bad input.
const VALIDATION_STATUSES = [400, 422, 428];

// Responses that mean "the handler ran correctly, there is just no such record".
const ABSENT_MARKERS = [
  "not found",
  "no such",
  "no pending",
  "doesn't exist",
  "required",
  "no data",
  "no records",
  "empty",
  "invalid",
  "cannot",
  "must be",
  "missing",
  "no active",
  "nothing",
];

const RED = "\x1b[31m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const DIM = "\x1b[2m";
const RESET = "\x1b[0m";

let authToken = null;

function request(method, path, body) {
  return new Promise((resolve) => {
    let url;
    try {
      url = new URL(path, BASE);
    } catch (err) {
      return resolve({ status: 0, body: "bad url: " + err.message });
    }

    const headers = { "Content-Type": "application/json" };
    if (authToken) headers["Authorization"] = "Bearer " + authToken;

    const req = http.request(
      {
        hostname: url.hostname,
        port: url.port,
        path: url.pathname + url.search,
        method,
        headers,
        timeout: TIMEOUT_MS,
      },
      (res) => {
        let data = "";
        res.on("data", (c) => (data += c));
        res.on("end", () => {
          let parsed = data;
          try {
            parsed = JSON.parse(data);
          } catch {
            /* keep raw */
          }
          resolve({ status: res.statusCode, body: parsed, raw: data });
        });
      },
    );

    req.on("timeout", () => {
      req.destroy();
      resolve({ status: 0, body: "TIMEOUT after " + TIMEOUT_MS + "ms" });
    });
    req.on("error", (err) => resolve({ status: 0, body: err.message }));

    if (body) req.write(JSON.stringify(body));
    req.end();
  });
}

function fillParams(path) {
  return path.replace(/:([A-Za-z_]+)/g, (_, name) => PARAM_PROBES[name] ?? "1");
}

function shortBody(body) {
  if (body === undefined || body === null) return "";
  const s = typeof body === "string" ? body : JSON.stringify(body);
  return s.length > 110 ? s.slice(0, 110) + "…" : s;
}

function looksAbsent(status, body) {
  if (status !== 404 && status !== 400 && status !== 409) return false;
  const s = (typeof body === "string" ? body : JSON.stringify(body || "")).toLowerCase();
  return ABSENT_MARKERS.some((m) => s.includes(m)) || s.length < 200;
}

async function login() {
  const res = await request("POST", "/api/auth/login", {
    email: "admin@resort.com",
    password: "password",
  });
  const token = res.body && res.body.token;
  if (token) {
    authToken = token;
    return true;
  }
  return false;
}

async function main() {
  const args = process.argv.slice(2);

  let routes;
  try {
    routes = JSON.parse(require("fs").readFileSync(ROUTES_FILE, "utf8"));
  } catch (err) {
    console.error("Cannot read " + ROUTES_FILE + " — run: node /tmp/route-inventory.js");
    process.exit(2);
  }

  if (args.includes("--list")) {
    routes.forEach((r) => console.log(r.method.padEnd(7) + r.path));
    console.log("\n" + routes.length + " routes");
    return;
  }

  const gets = routes.filter((r) => r.method === "GET");
  const writes = routes.filter(
    (r) => ["POST", "PUT", "PATCH"].includes(r.method) && !SKIP_PROBE_PREFIXES.some((p) => r.path.startsWith(p)),
  );

  const readTests = [
    ...gets.map((r) => ({ method: "GET", path: r.path, label: "GET " + r.path, tier: "read" })),
    ...SAFE_WRITES.map((r) => ({ method: r.method, path: r.path, body: r.body, label: r.method + " " + r.path, tier: "read" })),
  ];

  const probeTests = args.includes("--no-probe")
    ? []
    : writes.map((r) => ({
        method: r.method,
        path: r.path,
        body: {},
        label: r.method + " " + r.path,
        tier: "probe",
      }));

  const tests = [...readTests, ...probeTests];

  console.log("\n" + "=".repeat(72));
  console.log(`  Resort API Suite — ${readTests.length} read + ${probeTests.length} write-probe`);
  console.log("=".repeat(72) + "\n");

  const gotToken = await login();
  console.log(gotToken ? GREEN + "🔑 Authenticated as admin" + RESET : YELLOW + "⚠️  No token — auth-required routes will report 401" + RESET);
  console.log("");

  const pass = [];
  const absent = [];
  const fail = [];
  const unverified = [];
  const wrote = [];
  const unimplemented = [];

  for (const t of tests) {
    const target = fillParams(t.path);
    const res = await request(t.method, target, t.body);
    const body = res.body;

    if (res.status === 0) {
      fail.push({ label: t.label, status: 0, detail: String(body) });
      console.log(`${RED}❌ ${t.label}${RESET} ${DIM}→ ${shortBody(body)}${RESET}`);
      continue;
    }

    if (res.status === 401 || res.status === 403) {
      unverified.push({ label: t.label, status: res.status, detail: shortBody(body) });
      console.log(`${YELLOW}🔒 ${t.label}${RESET} ${DIM}(${res.status} — auth/role)${RESET}`);
      continue;
    }

    if (t.tier === "probe") {
      // Probe tier: the question is "is this route wired to a working handler?",
      // so a validation rejection is the pass and an accepted write is flagged.
      if (VALIDATION_STATUSES.includes(res.status)) {
        pass.push(t.label);
        console.log(`${GREEN}✅ ${t.label}${RESET} ${DIM}(rejected empty body)`);
      } else if (res.status === 501) {
        unimplemented.push({ label: t.label, detail: shortBody(body) });
        console.log(`${YELLOW}🚧 ${t.label}${RESET} ${DIM}(501 Not implemented)`);
      } else if (res.status === 500) {
        fail.push({ label: t.label, status: 500, detail: shortBody(body) });
        console.log(`${RED}❌ ${t.label}${RESET} ${DIM}(500) ${shortBody(body)}${RESET}`);
      } else if (looksAbsent(res.status, body)) {
        absent.push({ label: t.label, status: res.status, detail: shortBody(body) });
        console.log(`${YELLOW}➖ ${t.label}${RESET} ${DIM}(${res.status}) ${shortBody(body)}${RESET}`);
      } else {
        // Route answered without rejecting — a real write happened on an empty body.
        wrote.push({ label: t.label, status: res.status, detail: shortBody(body) });
        console.log(`${YELLOW}✍️  ${t.label}${RESET} ${DIM}(${res.status} accepted empty body) ${shortBody(body)}${RESET}`);
      }
      continue;
    }

    if (res.status === 200 || res.status === 201) {
      pass.push(t.label);
      console.log(`${GREEN}✅ ${t.label}${RESET}`);
    } else if (looksAbsent(res.status, body)) {
      absent.push({ label: t.label, status: res.status, detail: shortBody(body) });
      console.log(`${YELLOW}➖ ${t.label}${RESET} ${DIM}(${res.status} — no such record)${RESET}`);
    } else {
      fail.push({ label: t.label, status: res.status, detail: shortBody(body) });
      console.log(`${RED}❌ ${t.label}${RESET} ${DIM}(${res.status}) ${shortBody(body)}${RESET}`);
    }
  }

  console.log("\n" + "=".repeat(72));
  console.log(
    `  ${GREEN}${pass.length} PASS${RESET}  |  ${fail.length} FAIL  |  ${absent.length} ABSENT  |  ${unverified.length} AUTH  |  ${unimplemented.length} STUB  |  ${wrote.length} WROTE`,
  );
  console.log("=".repeat(72));

  if (args.includes("--failures") || fail.length) {
    if (fail.length) {
      console.log("\n" + RED + "FAILURES (" + fail.length + ") — handler ran and broke:" + RESET);
      fail.forEach((f) => console.log("  • " + f.label + " [" + f.status + "] " + f.detail));
    }
  }

  if (absent.length) {
    console.log("\n" + YELLOW + "ABSENT (" + absent.length + ") — endpoint OK, no matching record:" + RESET);
    absent.forEach((f) => console.log("  • " + f.label + " [" + f.status + "] " + f.detail));
  }

  if (wrote.length) {
    console.log("\n" + YELLOW + "ACCEPTED EMPTY BODY (" + wrote.length + ") — check these create sensible rows:" + RESET);
    wrote.forEach((f) => console.log("  • " + f.label + " [" + f.status + "] " + f.detail));
  }

  if (unimplemented.length) {
    console.log("\n" + YELLOW + "NOT IMPLEMENTED (" + unimplemented.length + ") — route wired to a 501 stub:" + RESET);
    unimplemented.forEach((f) => console.log("  • " + f.label + " " + f.detail));
  }

  if (unverified.length) {
    console.log("\n" + YELLOW + "AUTH-GATED (" + unverified.length + "):" + RESET);
    unverified.forEach((f) => console.log("  • " + f.label + " [" + f.status + "] " + f.detail));
  }

  console.log("");
  process.exitCode = fail.length ? 1 : 0;
}

main().catch((err) => {
  console.error("runner error:", err);
  process.exit(1);
});
