ALTER TABLE tables
  ADD COLUMN floor_name VARCHAR(80) DEFAULT NULL,
  ADD COLUMN section_name VARCHAR(80) DEFAULT NULL,
  ADD COLUMN seat_count INT NOT NULL DEFAULT 4,
  ADD COLUMN status_color VARCHAR(30) DEFAULT NULL;

ALTER TABLE menu_items
  ADD COLUMN tax DECIMAL(6,2) NOT NULL DEFAULT 5,
  ADD COLUMN happy_hour_price DECIMAL(10,2) DEFAULT NULL,
  ADD COLUMN happy_hour_start TIME DEFAULT NULL,
  ADD COLUMN happy_hour_end TIME DEFAULT NULL;

ALTER TABLE bills
  ADD COLUMN waiter_name VARCHAR(191) DEFAULT NULL,
  ADD COLUMN split_no INT DEFAULT NULL,
  ADD COLUMN split_count INT DEFAULT NULL;

CREATE TABLE IF NOT EXISTS restaurant_item_action_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  token_item_id INT NOT NULL,
  table_number VARCHAR(50) NOT NULL,
  action_type VARCHAR(30) NOT NULL,
  reason TEXT NOT NULL,
  requested_by VARCHAR(191) DEFAULT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Pending',
  manager_note TEXT DEFAULT NULL,
  approved_by VARCHAR(191) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS restaurant_split_bills (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bill_id INT DEFAULT NULL,
  table_number VARCHAR(50) NOT NULL,
  entity_type VARCHAR(30) DEFAULT 'Table',
  split_label VARCHAR(80) NOT NULL,
  split_no INT NOT NULL,
  split_count INT NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL DEFAULT 0,
  gst DECIMAL(10,2) NOT NULL DEFAULT 0,
  total DECIMAL(10,2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(50) DEFAULT NULL,
  items_json LONGTEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
